---
- name: Instalação do IIS na instância EC2 com Windows Server 2019
  hosts: Servidores
  gather_facts: false
  vars:
    ansible_connection: winrm
    ansible_winrm_transport: basic
    ansible_winrm_server_cert_validation: ignore
    ansible_user: Administrator
    ansible_password: ykwcQ=ulAmiS9maM-gxSGVCVDC$?(&a8
    ansible_port: 5985
  tasks:
    - name: Instalação do IIS
      win_feature:
        name: Web-Server
        state: present
  
